# SPDX-FileCopyrightText: 2025 Luis Pfamminger
#
# SPDX-License-Identifier: Apache-2.0

name: check reuse compliance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  reuse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v4
